ci: streamline test startup

diff --git a/dojo/dojo b/dojo/dojo
--- a/dojo/dojo
+++ b/dojo/dojo
@@ -174,6 +174,16 @@ case "$ACTION" in
             esac
         done
 
+        if docker ps -a --format '{{.Names}}' | grep -q '^workspace-builder$'; then
+            docker wait workspace-builder
+            if ! docker ps -a | grep workspace-builder | grep "Exited (0)"
+            then
+                docker logs workspace-builder | tail -n100
+                echo "WORKSPACE BUILDER FAILED"
+                exit 1
+            fi
+        fi
+
         if docker ps --format '{{.Names}}' | grep -q '^stats-worker$'; then
             echo "Waiting for stats-worker cold start to complete..."
             timeout=300
