dojo: make wait handle workspace-builder exit

diff --git a/dojo/dojo b/dojo/dojo
--- a/dojo/dojo
+++ b/dojo/dojo
@@ -174,14 +174,12 @@ case "$ACTION" in
             esac
         done
 
-        if docker ps -a --format '{{.Names}}' | grep -q '^workspace-builder$'; then
-            docker wait workspace-builder
-            if ! docker ps -a | grep workspace-builder | grep "Exited (0)"
-            then
-                docker logs workspace-builder | tail -n100
-                echo "WORKSPACE BUILDER FAILED"
-                exit 1
-            fi
+        if docker inspect workspace-builder >/dev/null 2>&1 \
+            && ! docker wait workspace-builder
+        then
+            docker logs --tail 100 workspace-builder
+            echo "Error: workspace-builder failed"
+            exit 1
         fi
 
         if docker ps --format '{{.Names}}' | grep -q '^stats-worker$'; then
