Fix db backup/restore

diff --git a/dojo/dojo b/dojo/dojo
--- a/dojo/dojo
+++ b/dojo/dojo
@@ -84,14 +84,26 @@ case "$ACTION" in
 
     # HELP: db: launch a mysql client session, connected to the ctfd db
     "db")
-        docker exec $DOCKER_ARGS -e PGPASSWORD="${DB_PASS}" db psql -h "${DB_HOST}" -U "${DB_USER}" -d "${DB_NAME}" "$@"
+        [ $# -eq 0 ] && set -- psql
+        docker exec $DOCKER_ARGS -e PGHOST="${DB_HOST}" -e PGDATABASE="${DB_NAME}" -e PGUSER="${DB_USER}" -e PGPASSWORD="${DB_PASS}" db "$@"
         ;;
 
     # HELP: backup: does a dojo db backup into the `/data/backups` directory.
     "backup")
-        # PG-TODO: Fix this
         mkdir -p /data/backups
-        docker exec db mysqldump -h ${DB_HOST} -p${DB_PASS} -u${DB_USER} --single-transaction --routines --triggers ${DB_NAME} | gzip > "/data/backups/db-$(date -Iseconds).sql.gz"
+        BACKUP_PATH="/data/backups/db-$(date -Iseconds).dump"
+        dojo db pg_dump -Fc > "$BACKUP_PATH" </dev/null
+        echo "Created backup at $BACKUP_PATH"
+        ;;
+
+    # HELP: restore PATH: restores a dojo db backup. Path arg is relative to the `/data/backups` directory
+    "restore")
+        BACKUP_PATH="/data/backups/$1"
+        if [ -f "$BACKUP_PATH" ]; then
+            dojo db pg_restore --clean --if-exists --dbname="$DB_NAME" < "$BACKUP_PATH"
+        else
+            echo "Error: missing file to restore from" >&2
+        fi
         ;;
 
     # HELP: cloud-backup: upload the last day's worth of cloud backups to S3, but encrypt it at rest
@@ -111,17 +123,6 @@ case "$ACTION" in
             echo "backed up $OUT_FILE to S3 bucket $S3_BACKUP_BUCKET"
             rm "$OUT_FILE"
         done
-        ;;
-
-    # HELP: restore PATH: restores a dojo db backup. Path arg is relative to the `/data/backups` directory
-    "restore")
-        # PG-TODO: Fix this
-        BACKUP_PATH="/data/backups/$1"
-        if [ -f "$BACKUP_PATH" ]; then
-            gunzip < "$BACKUP_PATH" | docker exec -i db mysql -h ${DB_HOST} -p${DB_PASS} -u${DB_USER} -D${DB_NAME}
-        else
-            echo "Error: missing file to restore from" >&2
-        fi
         ;;
 
     # HELP: logs: display dojo logs
