database backup and restore

diff --git a/script/dojo b/script/dojo
--- a/script/dojo
+++ b/script/dojo
@@ -39,7 +39,17 @@ case "$ACTION" in
         ;;
 
     "backup")
-        docker exec db mysqldump -pctfd --single-transaction --routines --triggers ctfd > "/tmp/db-backup-$(date -Iseconds).sql"
+        mkdir -p data/backups
+        docker exec db mysqldump -pctfd --single-transaction --routines --triggers ctfd | gzip > "data/backups/db-$(date -Iseconds).sql.gz"
+        ;;
+
+    "restore")
+        BACKUP_PATH="data/backups/$1"
+        if [ -f "$BACKUP_PATH" ]; then
+            gunzip < "$BACKUP_PATH" | docker exec -i db mysql -pctfd -Dctfd
+        else
+            echo "Error: missing file to restore from" >&2
+        fi
         ;;
 
     "logs")
