Improve logging and fix tests

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -32,30 +32,37 @@ jobs:
 
       - name: Wait for services to be started
         run: |
+          docker exec dojo-test dojo logs -f &
+          log_pid=$!
+
           until docker exec dojo-test dojo is-setup-finished
           do
             sleep 5
-            docker exec dojo-test journalctl -u pwn.college | grep "Failed to start pwn.college docker compose service." && exit -1
-            docker exec dojo-test journalctl -u pwn.college  | tail -n 5
+            docker exec dojo-test dojo logs | grep "Failed to start pwn.college docker compose service." && (kill $log_pid; exit 1)
           done
 
       - name: Wait for services to be running
         run: |
+          docker exec dojo-test dojo compose logs -f &
+          log_pid=$!
+
           start_time=$(date +%s)
           timeout=120
 
-          until [[ "$(docker inspect --format='{{.State.Health.Status}}' ctfd)" == "healthy" ]]; do
+          until [[ "$(docker exec dojo-test docker inspect --format='{{.State.Health.Status}}' ctfd)" == "healthy" ]]; do
             current_time=$(date +%s)
             elapsed_time=$((current_time - start_time))
 
             if [[ "$elapsed_time" -ge "$timeout" ]]; then
-              echo "Timeout after waiting for 120 seconds. Services not healthy."
+              kill $log_pid
+              echo "Timeout after waiting for $timeout seconds!"
               exit 1
             fi
 
-            sleep 5
-            docker exec dojo-test dojo logs | tail -n 5
+            sleep 1
           done
+
+          kill $log_pid
 
       - name: Run tests against container
         run: |
